language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: javiersvg-github
    token:
      secure: ${SONAR_TOKEN}
    github_token:
      secure: ${GITHUB_TOKEN}
script: "./gradlew build jacocoTestReport sonarqube"
before_deploy:
      - git config --local user.name "Travis CI"
      - git config --local user.email "automatic@travis-ci.org"
      - git tag "$(./gradlew properties -q | grep version | awk '{print $2}')"-${TRAVIS_BUILD_NUMBER}
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  overwrite: true