language: java
jdk:
- oraclejdk8
addons:
  sonarcloud:
    organization: javiersvg-github
    token:
      secure: ${SONAR_TOKEN}
    github_token:
      secure: ${GITHUB_TOKEN}
script: "./gradlew build jacocoTestReport sonarqube"
deploy:
  provider: releases
  api_key:
    secure: ${GITHUB_TOKEN}
  file_glob: true
  file: build/libs/*.jar
  skip_cleanup: true
  on:
    tags: true