logging:
  path: log/
  level.org.springframework.security.oauth2: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs