logging:
  path: log/
  level.org.springframework.security.oauth2: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            client-id: 204566820246-67tser74gtv78uiaskm945enn5b5agl2.apps.googleusercontent.com
            client-secret: t0hCLNRZqpQUrQyrEgA_TixL