name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        env:
          github.token: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_github.token: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build publish
